Numero = input('Digite um numero de 4 digitos: ')
print('Unidade: {}' .format(Numero[3]))
print('Dezena: {}' .format(Numero[2]))
print('Centena: {}' .format(Numero[1]))
print('Milhar: {}' .format(Numero[0]))