a = input('Digite algo:')
print('Qual tipo primitivo desse valor?', type())
print('Só tem espaços?', a.isspace())
print('É um número?', a.isnumeric())
print('É alfabetico?', a.isalpha())
print('É alfanumerico?', a.isalnum())
print('Está em maiusculo?', a.isupper())
print('Esta em minusculo?', a.islower())
print('Esta capitalizado?', a.istitle())